export const AGENDA_PERMISSIONS = {
 APP_ACCESS:'AGENDA.APP.ACCESS', EVENTS_VIEW:'AGENDA.EVENTS.VIEW', EVENTS_MANAGE:'AGENDA.EVENTS.MANAGE',
 REGISTRATION_CREATE:'AGENDA.REGISTRATION.CREATE', REGISTRATION_VIEW:'AGENDA.REGISTRATION.VIEW',
 ATTENDANCE_MANAGE:'AGENDA.ATTENDANCE.MANAGE', COMMITMENTS_VIEW:'AGENDA.COMMITMENTS.VIEW',
 COMMITMENTS_MANAGE:'AGENDA.COMMITMENTS.MANAGE', ACTA_VIEW:'AGENDA.ACTA.VIEW',
 ACTA_UPLOAD:'AGENDA.ACTA.UPLOAD', ACTA_SIGN:'AGENDA.ACTA.SIGN'
} as const;
